railsgirls/guides-ptbr

_posts/2014-01-30-anynines.markdown
Esse PR traduz o artigo [2014-01-30-anynines.markdown](https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2014-01-30-anynines.markdown).
Fiquei um pouco em dúvida em como traduzir alguns termos e se algumas frases faziam sentido depois de traduzidas de forma literal para o português. Por isso, aguardo comentários com sugestões de alterações, caso julguem necessário.
Estou à disposição.
=> Tradução para português - Anynines

_posts/2014-05-10-ruby-atm.markdown, index.html
Além da tradução, fiz uma localização para mudar a moeda para Real e linkar para o artigo da Wikipedia em português.
=> Tradução do artigo ruby-atm

_posts/2014-01-30-continuous-codeship.markdown
Tradução 2014-01-30-continuous-codeship
=> Tradução 2014-01-30-continuous-codeship

_posts/2014-05-29-touristic-autism_resource-rating.markdown
=> Tradução 2014-05-29-touristic-autism_resource-rating.markdown

_posts/2014-05-10-sinatra.markdown
Tradução do arquivo 2014-05-10-sinatra-markdown para pt-br
=> 2014-05-10-sinatra-markdown

_posts/2012-04-18-guide.markdown
=> Translate file to pr-br

_posts/2014-10-02-sinatra-app-tutorial.markdown
Finalizada tradução do arquivo 2014-10-02-sinatra-app-tutorial.markdown
=> Adicionada Tradução 2014-05-10-sinatra-app-tutorial

_posts/2014-05-29-touristic-autism_google-map.markdown
Tradução do arquivo 2014-05-29-touristic-autism_google-map.markdown .
=> Arquivo 2014-05-29-touristic-autism_google-map.markdown

_posts/2014-10-05-diary-app.markdown
=> Translate diary app markdown

index.html
Olá!
*O título e o nome da branch se autodescrevem :)*
=> Arrumar "Gilrs" -> "Girls" typo

_posts/2012-04-18-app.markdown
Atualização a tradução do App Post.
Issue: https://github.com/railsgirls/guides-ptbr/issues/44
=> Update App Post

_posts/2016-08-30-activeadmin.markdown
Foi finalizado a tradução da página do Active Admin 
Issue: https://github.com/railsgirls/guides-ptbr/issues/48
=> Finished translation of active admin

_posts/2014-01-30-testing.markdown
O tutorial do RSpec foi atualizado: http://guides.railsgirls.com/testing-rspec :)
Arquivo em inglês: http://guides.railsgirls.com/testing-rspec
Arquivo em português: http://guides.railsgirls.com/guides-ptbr/testing-rspec
=> Atualizando 2014-01-30-testing.markdown

_posts/2017-08-13-shoulda-matchers.markdown, index.html
Foi criado o post do shoulda matchers traduzido.
=> added post shoulda matchers

_posts/2018-02-01-passenger.markdown, index.html
Foi adicionado o post do passenger para português.
=> Create pushion passeger translate for portuguese

_posts/2015-09-11-continuous-snap-ci.markdown
Resolvendo a issue #73 e traduzindo a postagem sobre o deploy contínuo com Snap Ci. 
Revisões ao texto e a tradução são mais do que bem-vindas. :+1:
=> Post snapci

_posts/2014-01-30-testing.markdown
=> Tradução PT-BR 2014-01-30-testing.markdown

_posts/2017-08-13-shoulda-matchers.markdown
=> Atualização do post 2017-08-13-shoulda-matchers.markdown

_posts/2014-05-29-touristic-autism_resource-modeling.markdown
=> Tradução de 2014-05-29-touristic-autism_resource-modeling

_posts/2012-04-18-guide.markdown
=> Refletindo mudança do tutorial principal (Remove Video).

_posts/2012-04-19-contributing.markdown, _posts/2012-04-30-commenting.markdown, _posts/2012-11-01-devise.markdown, _posts/2013-01-20-design.markdown, _posts/2013-04-14-github.md, _posts/2013-05-02-install.markdown, _posts/2013-07-23-bundlerfordevelopment.markdown, _posts/2013-08-12-guide-to-the-guide.markdown, _posts/2013-10-16-remote-pairing-for-the-win.markdown, _posts/2014-01-05-design-using-html-and-css.markdown, _posts/2014-01-30-continuous-codeship.markdown, _posts/2014-01-30-continuous-travis.markdown, _posts/2014-01-30-ruby-game.markdown, _posts/2014-02-13-simple-app.markdown, _posts/2014-05-10-ruby-atm.markdown, _posts/2014-05-10-sinatra-html.markdown, _posts/2014-05-10-sinatra.markdown, _posts/2014-05-29-touristic-autism_basic-app.markdown, _posts/2014-05-29-touristic-autism_continuous-deployment.markdown, _posts/2014-05-29-touristic-autism_git.markdown, _posts/2014-05-29-touristic-autism_resource-modeling.markdown, _posts/2014-05-29-touristic-autism_resource-rating.markdown, _posts/2014-10-02-sinatra-app-tutorial.markdown, _posts/2016-08-12-twitter-widget.markdown, _posts/2016-08-30-activeadmin.markdown
Resolve a issue #66 e como tive que verificar todos os arquivos de tutoriais, aproveitei pra corrigir alguns erros de markdown como:
- Textos itálicos com tag `<em>` ao invés do `_`
- Códigos inline que usavam três acentos(```) ao invés de um (`)
- Códigos highlight com linguagem errada, por exemplo, código erb com linguagem html
=> Verificar highlights e correções markdown

_posts/2014-01-30-testing.markdown
=> Correção do Rspec tutorial

_posts/2012-04-18-app.markdown, _posts/2012-06-03-thumbnails.markdown, _posts/2013-05-02-install.markdown, _posts/2014-02-13-simple-app.markdown, _posts/2014-03-24-alternative-dev-environment.markdown, _posts/2014-05-29-touristic-autism_basic-app.markdown, _posts/2014-05-29-touristic-autism_git.markdown, _posts/2014-05-29-touristic-autism_image-upload.markdown, index.html
Refletindo as mudanças do PR: railsgirls/railsgirls.github.io#424
=> Atualizar para nova marca da Apple (MacOS)

_posts/2013-05-02-install.markdown
=> Atualização do tutorial de instalação

_posts/2013-05-02-install.markdown
=> Atualiza a instalação do ruby/rails para windows

README.md
Hello, this is a little PR to add the badge to first timers friendly
[ISSUE](https://github.com/railsgirls/guides-ptbr/issues/67)
=> Added badge to first timers friendly

_posts/2021-04-05-docker.markdown, index.html
I created a small docker tutorial to teach people who want to use the docker and docker-compose to work with rails
=> create tutorial docker

_includes/other-guides.md
=> Corrige indicação de página atual em links das demais guias

_posts/2012-04-18-app.markdown, _posts/2012-04-19-heroku.markdown
- Adicionando o Visual Studio Code como editor na página /app
- Ajustando frase do prompt que estava confusa
- Adicionando informação sobre a gratuidade do Heroku
=> Pt-BR Suggestions and corrections
